name: ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 1 * * 1' # At 01:00 on Monday
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        ci_step: [
          "lint",
          "test",
          "integration tests",
        ]
        include:
          - ci_step: "lint"
            command: make lint
            go-cache: true
            linter-cache: true
            docker-cache: false
          - ci_step: "test"
            command: make test
            go-cache: true
            linter-cache: false
            docker-cache: false
          - ci_step: "integration tests"
            command: make integration-tests
            go-cache: true
            linter-cache: false
            docker-cache: true

    runs-on: ubuntu-22.04
    steps:
      - name: Go version used to build builder
        run: go version
      - name: Checkout faucet
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup go cache
        uses: actions/cache@v4
        if: ${{ matrix.go-cache }}
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Setup crust cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/crust
          key: ${{ runner.os }}-crust-${{ hashFiles('build/go.sum') }}
      - name: Setup linter cache
        uses: actions/cache@v4
        if: ${{ matrix.linter-cache }}
        with:
          path: ~/.cache/golangci-lint
          key: ${{ runner.os }}-go-linter
      - name: Set docker cache
        uses: ScribeMD/docker-cache@0.5.0
        if: ${{ matrix.docker-cache }}
        with:
          key: ${{ runner.os }}-docker-${{ hashFiles('build/go.sum') }}
      - name: Prepare dependencies
        run: make dependencies
      - name: Run ${{ matrix.ci_step }}
        run: ${{ matrix.command }}
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
