name: ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 1 * * 1' # At 01:00 on Monday
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        ci_step: [
          "lint",
          "test",
          "integration tests",
        ]
        include:
          - ci_step: "lint"
            command: make lint
          - ci_step: "test"
            command: make test
          - ci_step: "integration tests"
            command: make integration-tests

    runs-on: self-hosted
    steps:
      - name: Go version used to build builder
        run: go version
      - name: Checkout faucet
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Run ${{ matrix.ci_step }}
        run: ${{ matrix.command }}
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
