name: release
on:
  push:
#    branches:
#      - 'master'

env:
  REPO: faucet
  ORG: coreumfoundation

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set variables
        # if git tag is present, set FULL_IMAGE_NAME_WITH_GIT_TAG, else put empty string
        run: |
          echo "SHA8=${GITHUB_SHA::8}" >> $GITHUB_ENV
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)?$ ]]; then
              export FULL_IMAGE_NAME_WITH_GIT_TAG=format('{0}/{1}:{2}', env.ORG, env.REPO, github.ref_name)
          then
              export FULL_IMAGE_NAME_WITH_GIT_TAG=''
          fi
          echo "FULL_IMAGE_NAME_WITH_GIT_TAG=$FULL_IMAGE_NAME_WITH_GIT_TAG" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push faucet
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          # if tag is an empty string, plugin will skip that tag.
          tags: |
            ${{ env.ORG }}/${{ env.REPO }}:latest
            ${{ env.ORG }}/${{ env.REPO }}:${{ env.SHA8 }}
            ${{ env.FULL_IMAGE_NAME_WITH_GIT_TAG }}

