name: release
on:
  push:
#    tags:
#      - "v[0-9]+.[0-9]+.[0-9]+*"

env:
  REPO: faucet
  ORG: coreumfoundation

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo ::set-output name=release::true
          fi
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+$ ]]; then
              echo ::set-output name=release-candidate::true
          fi
      - name: Release
        if: steps.check-tag.outputs.release == 'true'
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
      - name: Release-candidate
        if: steps.check-tag.outputs.release-candidate == 'true'
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          generate_release_notes: true

      # docker part
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

#      - name: Prepare tags
#        id: prep
#        run: |
#          export TAG=`ruby -e 'puts File.read("package.json").match(/"version": "(?<semver>(0|[1-9][0-9]*).(0|[1-9][0-9]*).(0|[1-9][0-9]*))"/)[:semver]'`
#          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ env.ORG }}/${{ env.REPO }}:v1.1.1
          push: true
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}





